on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# on: [push]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        run: |
          npm install github-release-notes
          export PATH=$PATH:./node_modules/.bin
          gren changelog --override
          gren release --token=${{ secrets.GITHUB_TOKEN }} --override

