name: CI

on:
  release:
    types: [published]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: |
        echo $GITHUB_REF
        echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        echo ${GITHUB_REF:10} > version.txt
    - run: |
        pwd
        cat version.txt
      
