name: Upload Assets

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Set variables
        id: setenv
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
          echo ${GITHUB_REF:10} > version.txt
          echo ::set-output name=upload_url::$(curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${GITHUB_REF:10}" | jq ".upload_url") | sed -En "s/\{\?name\,label\}//p"
      - name: Create archive
        run: |
          zip readme.zip ./README.md 
          ls -al
          echo ${{ steps.setenv.outputs.upload_url }}
      - name: Upload Release Asset
        run: |
          export FILE=readme.zip
          echo $FILE
          curl \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: $(file -b --mime-type $FILE)" \
          --data-binary @$FILE \
          "${{ steps.setenv.outputs.upload_url }}?name=$(basename $FILE)"
          
        # id: upload-release-asset 
        # uses: actions/upload-release-asset@v1.0.1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   upload_url: ${{ steps.setenv.outputs.upload_url }}
        #   asset_path: ./readme.zip
        #   asset_name: readme.zip
        #   asset_content_type: application/zip

